# -*- coding: utf-8 -*-
"""Pengolahan Data PBL Sensor Sibi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KFqhmxo4d-5y8Fw-KN285WeGoXa0khiV
"""

# --- STEP 1: SETUP & UPLOAD ---
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import io
import numpy as np
from google.colab import files

# KONFIGURASI TAMPILAN JUMBO
# Mengatur gaya plot
sns.set_style("white")
# Ukuran font default diperbesar
plt.rcParams.update({'font.size': 12})

print("Silakan upload semua file Excel Anda...")
uploaded = files.upload()
filenames = list(uploaded.keys())

print(f"\n✅ Siap memproses {len(filenames)} file.")

# --- STEP 2: PROCESSING & TRIMMING (MAX 120 MENIT) ---

data_dict = {}

print("Memproses dan memotong data...")

for fname in filenames:
    try:
        # 1. Baca File
        df = pd.read_excel(io.BytesIO(uploaded[fname]))
        df.columns = df.columns.str.strip() # Hapus spasi

        # Cek header
        if 'Tanggal' not in df.columns:
            df = pd.read_excel(io.BytesIO(uploaded[fname]), header=1)
            df.columns = df.columns.str.strip()

        # 2. Gabung Tanggal & Jam
        df['Datetime'] = pd.to_datetime(df['Tanggal'].astype(str) + ' ' + df['Jam'].astype(str), dayfirst=True)
        df.set_index('Datetime', inplace=True)

        # 3. Konversi ke Numerik
        cols = ['Suhu', 'Kelembapan', 'Gas CO2', 'Gas NH3', 'Benzena']
        valid_cols = [c for c in cols if c in df.columns]
        for c in valid_cols:
            df[c] = pd.to_numeric(df[c], errors='coerce')

        # 4. RESAMPLING PER MENIT (Agar grafik detail untuk durasi pendek)
        # Menggunakan '1T' (1 Minute)
        df_resampled = df[valid_cols].resample('1T').mean().dropna()

        # 5. NORMALISASI WAKTU (Mulai dari 0)
        start_time = df_resampled.index.min()
        # Hitung menit berjalan
        df_resampled['Menit_Ke'] = (df_resampled.index - start_time).total_seconds() / 60

        # 6. PEMOTONGAN DATA (TRIMMING)
        # Hanya ambil data dari menit 0 sampai menit 120
        df_final = df_resampled[df_resampled['Menit_Ke'] <= 120].copy()

        if not df_final.empty:
            # Simpan
            data_dict[fname] = {
                'data': df_final,
                'original_start': start_time,
                'original_end': df_final.index.max() # Update end time sesuai potongan
            }
            durasi = df_final['Menit_Ke'].max()
            print(f"  -> File '{fname}' OK. (Dipotong s/d menit ke-{durasi:.0f})")
        else:
            print(f"  ⚠️ File '{fname}' kosong setelah diproses.")

    except Exception as e:
        print(f"  ❌ Gagal memproses '{fname}': {e}")

print("\n✅ Pemrosesan selesai.")

# --- STEP 3: GRAFIK OVERLAY (UKURAN BESAR & RAPI) ---

def plot_jumbo(column_name, title, y_label):
    # Ukuran Gambar SANGAT BESAR (Lebar 20, Tinggi 10)
    plt.figure(figsize=(20, 10))

    has_data = False

    # Loop data
    for fname, content in data_dict.items():
        df = content['data']
        if column_name in df.columns:
            plt.plot(df['Menit_Ke'], df[column_name], linewidth=2.5, label=fname)
            has_data = True

    if has_data:
        # Judul Besar
        plt.title(title, fontsize=24, fontweight='bold', pad=20)

        # Label Sumbu Besar
        plt.xlabel('Durasi (Menit)', fontsize=18, fontweight='bold')
        plt.ylabel(y_label, fontsize=18, fontweight='bold')

        # Atur Ukuran Angka di Sumbu (Ticks)
        plt.xticks(fontsize=14)
        plt.yticks(fontsize=14)

        # Batasi Sumbu X pas di 0 - 120
        plt.xlim(0, 120)

        # LEGENDA DI BAWAH (Agar tidak menutupi grafik)
        plt.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1),
                   fancybox=True, shadow=True, ncol=4, fontsize=14)

        plt.grid(True, linestyle='--', alpha=0.3) # Grid tipis transparan bantu baca
        sns.despine()

        # Layout adjustment agar legend tidak terpotong saat disimpan
        plt.tight_layout()
        plt.show()
    else:
        print(f"Skipping {column_name} (No Data)")

# --- CETAK SEMUA GRAFIK ---
plot_jumbo('Suhu', 'Perbandingan SUHU (0-120 Menit)', 'Suhu (°C)')
plot_jumbo('Kelembapan', 'Perbandingan KELEMBAPAN (0-120 Menit)', 'Kelembapan (%)')
plot_jumbo('Gas CO2', 'Perbandingan GAS CO2 (0-120 Menit)', 'Konsentrasi (ppm)')
plot_jumbo('Gas NH3', 'Perbandingan GAS NH3 (0-120 Menit)', 'Konsentrasi (ppm)')
plot_jumbo('Benzena', 'Perbandingan BENZENA (0-120 Menit)', 'Konsentrasi (ppm)')

# --- STEP 4 (FIXED - ALL INCLUDED): SUHU, KELEMBAPAN, GAS, SAFETY ---

LATITUDE = -6.2383
LONGITUDE = 106.9756
TIMEZONE = "Asia/Jakarta"

# --- KONSTANTA STANDAR ---
STD_CO2 = 420.0     # Baseline Outdoor (ppm)
STD_NH3 = 25.0      # Batas Bahaya ACGIH (ppm)
STD_BENZENA = 1.0   # Batas Bahaya OSHA (ppm)

bias_results = []

print("Sedang memproses validasi data lengkap (Suhu, Lembab, Gas)...")

for fname, content in data_dict.items():
    df_sensor = content['data']
    start_dt = content['original_start']
    end_dt = content['original_end']

    # 1. AMBIL DATA CUACA (Open-Meteo)
    df_ref_weather = pd.DataFrame()
    try:
        s_str = start_dt.strftime('%Y-%m-%d')
        e_str = end_dt.strftime('%Y-%m-%d')
        url = f"https://archive-api.open-meteo.com/v1/archive?latitude={LATITUDE}&longitude={LONGITUDE}&start_date={s_str}&end_date={e_str}&hourly=temperature_2m,relative_humidity_2m&timezone={TIMEZONE}"
        resp = requests.get(url).json()

        if 'hourly' in resp:
            df_ref_weather = pd.DataFrame({
                'Datetime': pd.to_datetime(resp['hourly']['time']),
                'Suhu_Ref': resp['hourly']['temperature_2m'],
                'Hum_Ref': resp['hourly']['relative_humidity_2m']
            })
            df_ref_weather.set_index('Datetime', inplace=True)
    except:
        pass # Lanjut jika gagal koneksi

    # 2. HITUNG BIAS & MARGIN
    # A. Hitung Bias Suhu/Lembab (Butuh join waktu)
    bias_temp = np.nan
    bias_hum = np.nan

    if not df_ref_weather.empty:
        # Resample sensor ke jam agar bisa di-join
        df_hourly = df_sensor.resample('H').mean()
        df_merge = df_hourly.join(df_ref_weather, how='inner')
        if not df_merge.empty:
            bias_temp = (df_merge['Suhu'] - df_merge['Suhu_Ref']).mean()
            bias_hum = (df_merge['Kelembapan'] - df_merge['Hum_Ref']).mean()

    # B. Hitung Bias CO2 & Margin Safety (Pakai rata-rata total sensor)
    avg_sensor = df_sensor.mean()

    # Bias CO2 (Sensor - 420)
    bias_co2 = avg_sensor.get('Gas CO2', 0) - STD_CO2

    # Margin Safety (Sensor - Batas Bahaya)
    # Jika hasil Negatif = AMAN (Di bawah batas)
    margin_nh3 = avg_sensor.get('Gas NH3', 0) - STD_NH3
    margin_benz = avg_sensor.get('Benzena', 0) - STD_BENZENA

    bias_results.append({
        'File': fname,
        'Bias_Suhu': bias_temp,
        'Bias_Kelembapan': bias_hum,
        'Bias_CO2': bias_co2,
        'Margin_NH3': margin_nh3,
        'Margin_Benzena': margin_benz
    })

# --- 3. VISUALISASI ---
if bias_results:
    df_res = pd.DataFrame(bias_results)

    def plot_bar(col, title, y_lab, mode='bias'):
        plt.figure(figsize=(12, 6))
        df_clean = df_res.dropna(subset=[col])
        if df_clean.empty: return

        # Logika Warna
        if mode == 'safety':
            # Safety: Negatif (Hijau/Aman), Positif (Merah/Bahaya)
            colors = ['salmon' if x >= 0 else 'mediumaquamarine' for x in df_clean[col]]
        else:
            # Bias: Positif (Merah/Lebih Tinggi), Negatif (Biru/Lebih Rendah)
            colors = ['salmon' if x >= 0 else 'skyblue' for x in df_clean[col]]

        ax = sns.barplot(x='File', y=col, data=df_clean, palette=colors)
        plt.axhline(0, color='black', linewidth=1)
        plt.title(title, fontsize=16, fontweight='bold')
        plt.ylabel(y_lab, fontsize=12)
        plt.xticks(rotation=45, ha='right')

        # Label Angka
        for p in ax.patches:
            h = p.get_height()
            offset = 15 if h>=0 else -15
            ax.annotate(f'{h:.2f}', (p.get_x()+p.get_width()/2., h),
                        ha='center', va='center', xytext=(0, offset),
                        textcoords='offset points', fontweight='bold')
        sns.despine()
        plt.tight_layout()
        plt.show()

    # CETAK GRAFIK (Sekarang Lengkap)
    print("\n" + "="*20 + " GRAFIK VISUALISASI " + "="*20)
    plot_bar('Bias_Suhu', 'Akurasi: Bias SUHU (Sensor vs Open-Meteo)', 'Selisih (°C)', mode='bias')
    plot_bar('Bias_Kelembapan', 'Akurasi: Bias KELEMBAPAN (Sensor vs Open-Meteo)', 'Selisih (%)', mode='bias') # <--- SUDAH DITAMBAHKAN
    plot_bar('Bias_CO2', 'Akurasi: Bias CO2 (Sensor vs Baseline 420 ppm)', 'Selisih (ppm)', mode='bias')
    plot_bar('Margin_NH3', 'Safety Check: NH3 (Jarak dari Batas 25 ppm)', 'Margin (ppm)', mode='safety')
    plot_bar('Margin_Benzena', 'Safety Check: BENZENA (Jarak dari Batas 1 ppm)', 'Margin (ppm)', mode='safety')

    # --- 4. OUTPUT TEKS RANGKUMAN (LENGKAP) ---
    print("\n" + "="*60)
    print("      RANGKUMAN HASIL ANALISIS DATA (TEXT REPORT)")
    print("="*60)

    # RATA-RATA AKURASI
    avg_temp = df_res['Bias_Suhu'].mean()
    avg_hum = df_res['Bias_Kelembapan'].mean() # <--- SUDAH DITAMBAHKAN
    avg_co2 = df_res['Bias_CO2'].mean()

    print("A. ANALISIS AKURASI ALAT (BIAS)")
    print("-" * 35)

    print(f"1. SUHU")
    print(f"   Rata-rata Bias : {avg_temp:+.2f} °C")
    print(f"   (Status: Sensor cenderung {'LEBIH PANAS' if avg_temp > 0 else 'LEBIH DINGIN'} dari satelit)")

    print(f"\n2. KELEMBAPAN")
    print(f"   Rata-rata Bias : {avg_hum:+.2f} %")
    print(f"   (Status: Sensor cenderung {'LEBIH BASAH' if avg_hum > 0 else 'LEBIH KERING'} dari satelit)")

    print(f"\n3. GAS CO2")
    print(f"   Rata-rata Bias : {avg_co2:+.2f} ppm")
    print(f"   (Status: {'DI ATAS' if avg_co2 > 0 else 'DI BAWAH'} baseline udara segar 420 ppm)")

    # RATA-RATA SAFETY
    avg_nh3 = df_res['Margin_NH3'].mean()
    avg_benz = df_res['Margin_Benzena'].mean()

    print("\n" + "="*60)
    print("B. ANALISIS KESELAMATAN (SAFETY CHECK)")
    print("-" * 35)

    print(f"1. AMONIA (NH3)")
    print(f"   Batas Aman     : {STD_NH3} ppm")
    print(f"   Rata-rata Margin: {avg_nh3:+.2f} ppm")
    if avg_nh3 < 0:
        print("   ✅ KESIMPULAN: AMAN (Kadar rata-rata di bawah batas bahaya).")
    else:
        print("   ⚠️ KESIMPULAN: BERBAHAYA (Melebihi ambang batas!).")

    print(f"\n2. BENZENA")
    print(f"   Batas Aman     : {STD_BENZENA} ppm")
    print(f"   Rata-rata Margin: {avg_benz:+.2f} ppm")
    if avg_benz < 0:
        print("   ✅ KESIMPULAN: AMAN (Kadar rata-rata di bawah batas bahaya).")
    else:
        print("   ⚠️ KESIMPULAN: BERBAHAYA (Karsinogenik melebihi batas!).")
    print("="*60)

else:
    print("❌ Tidak ada data yang berhasil diproses.")